import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// app/layout.js

import './globals.css';
import 'swiper/css'; // <-- AÑADE ESTA LÍNEA
import 'swiper/css/autoplay'; // <-- AÑADE ESTA LÍNEA
import 'swiper/css/navigation'; // <-- AÑADE ESTA LÍNEA

// ... (el resto de tu archivo layout.js)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
